/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  PoseidonT3,
  PoseidonT3Interface,
} from "../../../contracts/Poseidon.sol/PoseidonT3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "input",
        type: "uint256[2]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61028a610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100355760003560e01c806329a5f2f61461003a575b600080fd5b610054600480360381019061004f91906101fd565b61006a565b6040516100619190610239565b60405180910390f35b6000919050565b6000604051905090565b600080fd5b600080fd5b6000601f19601f8301169050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b6100ce82610085565b810181811067ffffffffffffffff821117156100ed576100ec610096565b5b80604052505050565b6000610100610071565b905061010c82826100c5565b919050565b600067ffffffffffffffff82111561012c5761012b610096565b5b602082029050919050565b600080fd5b6000819050919050565b61014f8161013c565b811461015a57600080fd5b50565b60008135905061016c81610146565b92915050565b600061018561018084610111565b6100f6565b9050806020840283018581111561019f5761019e610137565b5b835b818110156101c857806101b4888261015d565b8452602084019350506020810190506101a1565b5050509392505050565b600082601f8301126101e7576101e6610080565b5b60026101f4848285610172565b91505092915050565b6000604082840312156102135761021261007b565b5b6000610221848285016101d2565b91505092915050565b6102338161013c565b82525050565b600060208201905061024e600083018461022a565b9291505056fea2646970667358221220e6a69c864dce43c522c5c1b6eb4102856af3c6c916dcceaecbab5f903152993b64736f6c63430008120033";

type PoseidonT3ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PoseidonT3ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PoseidonT3__factory extends ContractFactory {
  constructor(...args: PoseidonT3ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PoseidonT3> {
    return super.deploy(overrides || {}) as Promise<PoseidonT3>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PoseidonT3 {
    return super.attach(address) as PoseidonT3;
  }
  override connect(signer: Signer): PoseidonT3__factory {
    return super.connect(signer) as PoseidonT3__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoseidonT3Interface {
    return new utils.Interface(_abi) as PoseidonT3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoseidonT3 {
    return new Contract(address, _abi, signerOrProvider) as PoseidonT3;
  }
}
